#!/bin/bash

docker ps -a | tail -n +2 | awk '{print NR"\t" $0}'

echo "instance number?"
echo -n "- "
read -e n
id=$(docker ps -a | tail -n +2 | awk '{print NR" " $0}' | sed -n ${n}p | cut -d" " -f2)
winpty docker exec -it $id /bin/bash
